### ISSUE TITLE
比較関数の呼び出し回数がアルゴリズムによって異なる

### ISSUE THREAD

**Issue by yumetodo** [yumetodo/qsort#2]
>https://qiita.com/t-kawa/items/99408891b18bd1f87ae6#comment-cbc519b3d0828696bd32
>2018-06-10 15:29 のご投稿の先頭４行（一部修正）が次のようになっています。
>
>qsort d=-3 e=10000 s=8 0 M000:000:000:0: c=154580 1545800768 a=0 0 i=154580 T=15.20 152
>qs9e17 d=-3 e=10000 s=8 0 M140:900:000:0: c=128181 1281810481 a=0 0 i=128181 T=7.93 79
>qs10a5 d=-3 e=10000 s=8 0 M140:900:400:0: c=128173 1281734178 a=0 0 i=128173 T=10.00 100
>qs10a5m d=-3 e=10000 s=8 0 M140:900:400:0: c=128194 1281944284 a=0 0 i=128194 T=10.96 110
>
>比較関数の呼び出し回数　1281810481　1281734178　1281944284　が同じになっていないのは
なぜなのでしょうか？　random() を rand() に修正してもらっている影響でしょうか？

**Comment by yumetodo** [comment]
>random() を rand() 

これは関係ない。

qsortの呼び出し側を確認したが、`cmpfnc`以外からグローバル変数の`cmp_cnt`が書き換わる余地はないと判明したので、ソート関数の移植に失敗している可能性。

**Comment by yumetodo** [comment]
ソート関数の移植とは言うけど、ソート呼び出し側は結構書き換えてるけど、ソート関数はコンパイラの警告潰しただけだからなぁ・・・

unsignedな整数型に変えたものが0以下の値を設定しようとして巨大な数に循環してどっかのループ的な何かが早く打ち切られてしまっているとか・・・？

**Comment by akinomyoga** [comment]
毎回異なる乱数を用いているのが原因です。比較回数はソート前の排列に依存しますから。比較が目的の場合には、一度決めた種を固定して、共通のもので毎回初期化 (`random_engine().seed(...)`) しなければなりません。このような計測の場合には、再現性を担保する必要がありますので、

- (1) もし `random_device` などを使用する場合にはその時に使用した種もファイルに出力して、いつでも要求された時に種を開示できるようにしておく必要があります。
- (2) 或いは、手で決め打ちの種をソースコード内に書き込んでも良いです。

特に、今回のように、何度も実行することが目的ではない場合は (2) を用いることの方が一般的です。現に、元のソースコードでは `div_val + arr_max + 556` を固定の種として用いていたようです。

**Comment by yumetodo** [comment]
あーseedか・・・

**Comment by yumetodo** [comment]
https://github.com/yumetodo/qsort/blob/d7e55087521c2c3bd61b3175e978e40256a223dd/main_prog.cpp#L20
を消し飛ばして
https://github.com/yumetodo/qsort/blob/d7e55087521c2c3bd61b3175e978e40256a223dd/main_prog.cpp#L29-L41
を

```cpp
constexpr auto seed = U"glibc newlib より速いクイックソート(qs9 qs10)、 世界最速をめざしてqsortの新しいアルゴリズム qs9 を開発しましたその結果、ソート対象によっては間接ソートを取り入れた方が高速なことが判りました。今回、間接ソートを取り入れた qs10 を開発しました。お願い現在、 標準qsort　qs9　qs10　を比較するベンチマークテストを行っております。"
 std::mt19937 create_random_engine() 
 { 
 	std::seed_seq seq(std::begin(seed), std::end(seed)); 
 	return std::mt19937(seq); 
} 
```

とかに書き換えれば解決？

**Comment by akinomyoga** [comment]
んー。比較回数の問題はそれで解決すると思う。

序でだからもっと書いておくと、元のコードでは `do_qsort(1);` の前だけで種を設定しているけれど、これは微妙。乱数生成器はアルゴリズムにもよるけれども生成器の状態によってかかる時間が一定しないことがある (乱数生成器は償却計算量で考えることが多い。償却計算量で O(1) でもそれは飽くまで償却計算量) ので、`do_qsort(0);` を呼び出す前にも同じ種を設定して同一の状態になるようにした方が良い気がする。

元のコードで使っている [POSIX `random`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/initstate.html) は、*a non-linear additive feedback random-number generator* を使えってアルゴリズムが指定されているっぽい。この non-linear additive feedback RNG が償却計算量で一定なのか普通に計算量が一定なのかは知らない。

というかシングルトンで持たなくて良くない? `do_qsort` の一番最初に `auto eng = create_random_engine();` とかやればOKの気がする。

**Comment by yumetodo** [comment]
まあ確かにそうだ。
今Boost 1.67の絶賛ビルド中なので終わったら治す。
